apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: test
      port: 9090
      type: REST
      networkVisibility: Public
      context: /
      schemaFilePath: swagger.yaml
